<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Coding standard
|--------------------------------------------------------------------------
|
| The framework's own config, `vendor/hypervel/components/.php-cs-fixer.php`
| on the 0.4 branch. Its rules are imported, verbatim, as
| .github/php-cs-fixer-rules.php, shared by every ipsocode/hypervel-* package;
| everything else here is copied from it, except this header, the finder and
| the cache file.
|
| ---------------------------------------------------------------------------
| Read this before running the fixer on this package
| ---------------------------------------------------------------------------
|
| `setRiskyAllowed(true)` is on, and `declare_strict_types` is a risky rule:
| it changes behaviour, not formatting. A file that leans on PHP's coercive
| typing — an int reaching `preg_replace()`'s string-only $replacement, a rule
| argument reaching `str_repeat()`'s int $times, a PhpParser Node\Name reaching
| `mb_strpos()` — turns that silent coercion into a TypeError once the
| declaration lands. `src/` is clean under this config, but a change can bring
| one back: run `composer test` after `composer lint:fix`, never just before
| committing the diff.
|
| `return_assignment` is a second one to watch, for a reason specific to what
| this package does: it rewrites `$x = $request->validate([...]); return $x;`
| into `return $request->validate([...]);`, and Scribe's inline-validator
| strategies match a validation *statement*, so the rewrite silently turns a
| documented endpoint into an undocumented one. The Workbench controllers are
| written so the validated data is genuinely used, which keeps both the rule
| and the strategies happy.
|
| `php_unit_method_casing` renames test methods to camelCase, so a test written
| in snake_case is renamed out from under you on the next run.
|
*/

use PhpCsFixer\Config;
use PhpCsFixer\Runner\Parallel\ParallelConfig;

$maxProcesses = function_exists('swoole_cpu_num') ? swoole_cpu_num() : 4;

return (new Config)
    ->setParallelConfig(new ParallelConfig($maxProcesses))
    ->setRiskyAllowed(true)
    ->setRules(require __DIR__ . '/.github/php-cs-fixer-rules.php')
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('vendor')
            // The Workbench application's runtime storage — gitignored, and
            // regenerated by the Testbench skeleton on every boot.
            ->exclude('workbench/storage')
            // The tools' caches; php-cs-fixer v4 no longer skips dot-directories.
            ->exclude('tests/.cache')
            // Vendored third-party code: a re-namespaced mpociot/reflection-docblock
            // with PHP 8.4 explicit-nullable types applied. Reformatting it to
            // house style makes diffing against upstream harder for no gain,
            // which is the same reason phpunit.xml keeps it out of coverage.
            ->exclude('src/Reflection')
            // Blade templates end in `.php`, so the default `*.php` name filter
            // picks them up and the fixer happily rewrites the PHP inside a
            // `@php` block or a raw PHP island. They are vendored templates
            // rather than this package's source, and the same diffing argument
            // as `src/Reflection` applies.
            ->notName('*.blade.php')
            ->in(__DIR__)
    )
    ->setCacheFile(__DIR__ . '/tests/.cache/php-cs-fixer.cache');
