<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Coding standard
|--------------------------------------------------------------------------
|
| The framework's own config, `vendor/hypervel/components/.php-cs-fixer.php`
| on the 0.4 branch. Its rules are imported, verbatim, as
| .github/php-cs-fixer-rules.php, shared by every ipsocode/hypervel-* package;
| everything else here is copied from it, except this header, the finder and
| the cache file.
|
| ---------------------------------------------------------------------------
| Read this before running the fixer on this package
| ---------------------------------------------------------------------------
|
| `setRiskyAllowed(true)` is on, and `declare_strict_types` is a risky rule:
| it changes behaviour, not formatting. Code that leans on PHP's coercive
| typing (an int reaching `preg_replace()`'s string $replacement, a value
| reaching `str_repeat()`'s int $times, a PhpParser Node\Name reaching
| `mb_strpos()`) throws a TypeError once the declaration is added. `src/` is
| clean under this config, but a change can bring such a call back: run
| `composer test` after `composer lint:fix`, not only before committing.
|
| `return_assignment` rewrites `$x = $request->validate([...]); return $x;`
| into `return $request->validate([...]);`. The inline-validator strategies
| match a validation *statement*, so the rewrite turns a documented endpoint
| into an undocumented one. The Workbench controllers use the validated data,
| which keeps both the rule and the strategies satisfied.
|
| `php_unit_method_casing` renames test methods to camelCase, so a test written
| in snake_case is renamed on the next run.
|
*/

use PhpCsFixer\Config;
use PhpCsFixer\Runner\Parallel\ParallelConfig;

$maxProcesses = function_exists('swoole_cpu_num') ? swoole_cpu_num() : 4;

return (new Config)
    ->setParallelConfig(new ParallelConfig($maxProcesses))
    ->setRiskyAllowed(true)
    ->setRules(require __DIR__ . '/.github/php-cs-fixer-rules.php')
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('vendor')
            // The Workbench application's runtime storage — gitignored, and
            // regenerated by the Testbench skeleton on every boot.
            ->exclude('workbench/storage')
            // The tools' caches. The finder skips dot-directories only outside
            // php-cs-fixer's future (v4) mode, so this one is excluded by name.
            ->exclude('tests/.cache')
            // Vendored third-party code: a re-namespaced mpociot/reflection-docblock
            // with PHP 8.4 explicit-nullable types applied. It is kept as its
            // authors wrote it rather than in this package's style, and
            // phpunit.xml keeps it out of coverage for the same reason: it is
            // not this package's code.
            ->exclude('src/Reflection')
            // Blade templates end in `.php`, so the default `*.php` name filter
            // picks them up, and the fixer would rewrite the PHP inside a `@php`
            // block or a raw PHP island.
            ->notName('*.blade.php')
            ->in(__DIR__)
    )
    ->setCacheFile(__DIR__ . '/tests/.cache/php-cs-fixer.cache');
