<?php

declare(strict_types=1);

namespace Ipsocode\Scribe\GroupedEndpoints;

use Closure;
use Exception;
use Hypervel\Support\Collection;
use Hypervel\Support\Str;
use Ipsocode\Camel\Camel;
use Ipsocode\Camel\Extraction\ExtractedEndpointData;
use Ipsocode\Camel\Output\OutputEndpointData;
use Ipsocode\Scribe\Commands\GenerateDocumentation;
use Ipsocode\Scribe\Exceptions\CouldntGetRouteDetails;
use Ipsocode\Scribe\Extracting\ApiDetails;
use Ipsocode\Scribe\Extracting\Extractor;
use Ipsocode\Scribe\Extracting\RouteDocBlocker;
use Ipsocode\Scribe\Matching\MatchedRoute;
use Ipsocode\Scribe\Matching\RouteMatcherInterface;
use Ipsocode\Scribe\Reflection\DocBlock\Tag;
use Ipsocode\Scribe\Tools\ConsoleOutputUtils as c;
use Ipsocode\Scribe\Tools\DocumentationConfig;
use Ipsocode\Scribe\Tools\ErrorHandlingUtils as e;
use Ipsocode\Scribe\Tools\PathConfig;
use Ipsocode\Scribe\Tools\Utils;
use Ipsocode\Scribe\Tools\Utils as u;
use ReflectionClass;
use Symfony\Component\Finder\SplFileInfo;
use Symfony\Component\Yaml\Yaml;

class GroupedEndpointsFromApp implements GroupedEndpointsContract
{
    public string $camelDir;

    public string $cacheDir;

    private DocumentationConfig $docConfig;

    private bool $encounteredErrors = false;

    public function __construct(
        private GenerateDocumentation $command,
        private RouteMatcherInterface $routeMatcher,
        protected PathConfig $paths,
        private bool $preserveUserChanges = true,
    ) {
        $this->docConfig = $command->getDocConfig();

        $this->camelDir = Camel::camelDir($this->paths);
        $this->cacheDir = Camel::cacheDir($this->paths);
    }

    public function get(): array
    {
        $groupedEndpoints = $this->extractEndpointsInfoAndWriteToDisk($this->routeMatcher, $this->preserveUserChanges);

        $this->extractAndWriteApiDetailsToDisk();

        return $groupedEndpoints;
    }

    public function hasEncounteredErrors(): bool
    {
        return $this->encounteredErrors;
    }

    protected function extractEndpointsInfoAndWriteToDisk(RouteMatcherInterface $routeMatcher, bool $preserveUserChanges): array
    {
        $latestEndpointsData = [];
        $cachedEndpoints = [];

        if ($preserveUserChanges && is_dir($this->camelDir) && is_dir($this->cacheDir)) {
            $latestEndpointsData = Camel::loadEndpointsToFlatPrimitivesArray($this->camelDir);
            $cachedEndpoints = Camel::loadEndpointsToFlatPrimitivesArray($this->cacheDir);
        }

        $routes = $routeMatcher->getRoutes($this->docConfig->get('routes', []));
        $endpoints = $this->extractEndpointsInfoFromHypervelApp($routes, $cachedEndpoints, $latestEndpointsData);

        $groupedEndpoints = collect($endpoints)->groupBy('metadata.groupName')->map(function (Collection $endpointsInGroup) {
            return [
                'name' => $endpointsInGroup->first(function (ExtractedEndpointData $endpointData) {
                    return ! empty($endpointData->metadata->groupName);
                })->metadata->groupName ?? '',
                'description' => $endpointsInGroup->first(function (ExtractedEndpointData $endpointData) {
                    return ! empty($endpointData->metadata->groupDescription);
                })->metadata->groupDescription ?? '',
                'endpoints' => $endpointsInGroup->toArray(),
            ];
        })->all();
        $this->writeEndpointsToDisk($groupedEndpoints);

        return $groupedEndpoints;
    }

    protected function writeEndpointsToDisk(array $grouped): void
    {
        Utils::deleteFilesMatching(
            $this->camelDir,
            fn (SplFileInfo $file) => ! Str::startsWith($file->getFilename(), 'custom.'),
        );
        Utils::deleteDirectoryAndContents($this->cacheDir);

        if (! is_dir($this->camelDir)) {
            mkdir($this->camelDir, 0o777, true);
        }

        if (! is_dir($this->cacheDir)) {
            mkdir($this->cacheDir, 0o777, true);
        }

        $fileNameIndex = 0;
        foreach ($grouped as $group) {
            $yaml = Yaml::dump(
                $group,
                20,
                2,
                Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE | Yaml::DUMP_OBJECT_AS_MAP | Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK
            );

            // Two digits, so a plain name sort in a file browser lists them in
            // order too. Camel reads them back in natural order either way.
            $fileName = sprintf('%02d.yaml', $fileNameIndex);
            ++$fileNameIndex;

            file_put_contents($this->camelDir . "/{$fileName}", $yaml);
            file_put_contents($this->cacheDir . "/{$fileName}", "## Autogenerated by Scribe. DO NOT MODIFY.\n\n" . $yaml);
        }
    }

    protected function extractAndWriteApiDetailsToDisk(): void
    {
        $apiDetails = $this->makeApiDetails();

        $apiDetails->writeMarkdownFiles();
    }

    protected function makeApiDetails(): ApiDetails
    {
        return new ApiDetails($this->paths, $this->docConfig, ! $this->command->option('force'));
    }

    protected function makeExtractor(): Extractor
    {
        return new Extractor($this->docConfig);
    }

    /**
     * @param MatchedRoute[] $matches
     *
     * @throws Exception
     */
    private function extractEndpointsInfoFromHypervelApp(array $matches, array $cachedEndpoints, array $latestEndpointsData): array
    {
        $extractor = $this->makeExtractor();

        // Indexed so each route's lookup below is not a linear scan.
        $cachedEndpoints = self::indexByUriAndMethods($cachedEndpoints);
        $latestEndpointsData = self::indexByUriAndMethods($latestEndpointsData);

        $parsedEndpoints = [];

        foreach ($matches as $routeItem) {
            $route = $routeItem->getRoute();

            $routeControllerAndMethod = u::getRouteClassAndMethodNames($route);
            // @codeCoverageIgnoreStart
            // getRouteClassAndMethodNames() either returns a usable pair or
            // throws, so isValidRoute() has nothing left to reject here.
            if (! $this->isValidRoute($routeControllerAndMethod)) {
                c::warn('Skipping invalid route: ' . c::getRouteRepresentation($route));

                continue;
            }
            // @codeCoverageIgnoreEnd

            if (! $this->doesControllerMethodExist($routeControllerAndMethod)) {
                c::warn('Skipping route: ' . c::getRouteRepresentation($route) . ' - Controller method does not exist.');

                continue;
            }

            if ($this->isRouteHiddenFromDocumentation($routeControllerAndMethod)) {
                c::warn('Skipping route: ' . c::getRouteRepresentation($route) . ': @hideFromAPIDocumentation was specified.');

                continue;
            }

            try {
                // Buffer warnings so they don't break the task output.
                c::startWarningBuffer();

                $this->command->outputComponents()->task(
                    c::getRouteRepresentation($route),
                    function () use ($extractor, $route, $cachedEndpoints, $latestEndpointsData, &$parsedEndpoints) {
                        $currentEndpointData = $extractor->processRoute($route);
                        // Carry over sections the user edited in the Camel files.
                        $currentEndpointData = $this->mergeAnyEndpointDataUpdates($currentEndpointData, $cachedEndpoints, $latestEndpointsData);
                        $parsedEndpoints[] = $currentEndpointData;

                        return true;
                    }
                );

                c::flushWarningBuffer();
            } catch (Exception $exception) {
                $this->encounteredErrors = true;
                c::flushWarningBuffer();
                e::dumpExceptionIfVerbose($exception);
            }
        }

        return $parsedEndpoints;
    }

    /**
     * @param array<string, array> $cachedEndpoints indexed by {@see self::indexByUriAndMethods()}
     * @param array<string, array> $latestEndpointsData indexed by {@see self::indexByUriAndMethods()}
     */
    private function mergeAnyEndpointDataUpdates(ExtractedEndpointData $endpointData, array $cachedEndpoints, array $latestEndpointsData): ExtractedEndpointData
    {
        $key = self::uriAndMethodsKey($endpointData->uri, $endpointData->httpMethods);

        $thisEndpointCached = $cachedEndpoints[$key] ?? null;
        if (! $thisEndpointCached) {
            return $endpointData;
        }

        $thisEndpointLatest = $latestEndpointsData[$key] ?? null;
        if (! $thisEndpointLatest) {
            return $endpointData;
        }

        // A section that differs between the cache and the Camel file was edited by the user.
        $properties = [
            'metadata',
            'headers',
            'urlParameters',
            'queryParameters',
            'bodyParameters',
            'responses',
            'responseFields',
        ];

        $changed = [];
        foreach ($properties as $property) {
            if ($thisEndpointCached[$property] !== $thisEndpointLatest[$property]) {
                $changed[] = $property;
            }
        }

        $thisEndpointLatest = OutputEndpointData::create($thisEndpointLatest);
        foreach ($changed as $property) {
            $endpointData->{$property} = $thisEndpointLatest->{$property};
        }

        return $endpointData;
    }

    /**
     * Keys a flat list of endpoint arrays by URI and HTTP methods. The first
     * endpoint with a given pair wins.
     *
     * @param array[] $endpoints
     * @return array<string, array>
     */
    private static function indexByUriAndMethods(array $endpoints): array
    {
        $index = [];
        foreach ($endpoints as $endpoint) {
            $index[self::uriAndMethodsKey($endpoint['uri'] ?? null, $endpoint['httpMethods'] ?? null)] ??= $endpoint;
        }

        return $index;
    }

    /**
     * A key two endpoints share exactly when their URIs and method lists are
     * identical (`===`): serialize() distinguishes a URI's type and a method
     * list's keys and order, as `===` does.
     */
    private static function uriAndMethodsKey(mixed $uri, mixed $httpMethods): string
    {
        return serialize([$uri, $httpMethods]);
    }

    private function isValidRoute(?array $routeControllerAndMethod): bool
    {
        if (is_array($routeControllerAndMethod)) {
            if (count($routeControllerAndMethod) < 2) {
                throw CouldntGetRouteDetails::new();
            }
            [$classOrObject, $method] = $routeControllerAndMethod;
            if (u::isInvokableObject($classOrObject)) {
                return true;
            }
            $routeControllerAndMethod = $classOrObject . '@' . $method;
        }

        return ! is_callable($routeControllerAndMethod) && ! is_null($routeControllerAndMethod);
    }

    private function doesControllerMethodExist(array $routeControllerAndMethod): bool
    {
        // @codeCoverageIgnoreStart
        // isValidRoute() has already thrown on a pair this short.
        if (count($routeControllerAndMethod) < 2) {
            throw CouldntGetRouteDetails::new();
        }
        // @codeCoverageIgnoreEnd
        [$class, $method] = $routeControllerAndMethod;
        $reflection = new ReflectionClass($class);

        if ($reflection->hasMethod($method)) {
            return true;
        }

        return false;
    }

    private function isRouteHiddenFromDocumentation(array $routeControllerAndMethod): bool
    {
        if (! ($class = $routeControllerAndMethod[0]) instanceof Closure) {
            $classDocBlock = RouteDocBlocker::forClass($class);
            $shouldIgnoreClass = collect($classDocBlock->getTags())
                ->filter(function (Tag $tag) {
                    return Str::lower($tag->getName()) === 'hidefromapidocumentation';
                })->isNotEmpty();

            if ($shouldIgnoreClass) {
                return true;
            }
        }

        $methodDocBlock = RouteDocBlocker::forMethod(u::getReflectedRouteMethod($routeControllerAndMethod));
        $shouldIgnoreMethod = collect($methodDocBlock->getTags())
            ->filter(function (Tag $tag) {
                return Str::lower($tag->getName()) === 'hidefromapidocumentation';
            })->isNotEmpty();

        return $shouldIgnoreMethod;
    }
}
